language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-library' ]; then cd .. && eval "mv $currentfolder generator-library" && cd generator-library; fi

